Ansible 3
otus-devops-2019-02/SashaShip_infra pull request #12
Opened 2019-06-11 10:08 UTC by SashaShip

# Выполнено ДЗ 11

 - [ ] Основное ДЗ

2019-06-11 18:41 UTC, mrgreyves requested changes
Здравствуйте!) Вам нужно заполнить пр, так починить тесты. Возвращаю на доработку.

2019-06-24 13:08 UTC, SashaShip commented
Вот такую ошибку проверка показывает:

Could not fetch inspec profile in "otus-homeworks/homeworks/ansible-3".
The command "curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh | bash" failed and exited with 1 during .

2019-06-25 12:36 UTC, SashaShip commented
Просьба подтвердить

2019-06-25 16:12 UTC, mrgreyves approved these changes
Здравствуйте!) Проверил ваше дз. Смотрю Вы нашли ошибку. ДЗ принимаю!=)

2019-06-26 05:13 UTC, merged