Bastion
otus-devops-2019-02/SashaShip_infra pull request #2
Opened 2019-04-14 13:09 UTC by SashaShip

2019-04-14 13:53 UTC, mrgreyves requested changes
Здравствуйте!) Это домашнее задание? Нужно бы тогда заполнить описание пуллреквеста =)

2019-04-16 07:52 UTC, merged

2019-07-02 10:34 UTC, SashaShip commented
ПРосьба засчитать работу.

2019-07-02 10:34 UTC, SashaShip reviewed
Просьба засчитать рабту.

2019-07-17 07:17 UTC, SashaShip reviewed
Done