Terrafom
otus-devops-2019-02/SashaShip_infra pull request #6
Opened 2019-04-19 07:56 UTC by SashaShip

# Выполнено ДЗ № 8

 - [ x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Определение input переменных
 - Создан Travis

## Как запустить проект:
 - terraform apply

## Как проверить работоспособность:
 - 35.240.118.131:9292

## PR checklist
 - [ x] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2019-04-22 07:43 UTC, mrgreyves requested changes
Здравствуйте!) Постарайтесь починить тесты. Судя по всему не хватает файлов. Пока возвращаю на доработку.

2019-04-29 09:11 UTC, mrgreyves requested changes
Здравствуйте!) Снова не проходят тесты( Вам нужно удалить из репозитория лишние файлы. В частности стейты терраформа. Возвращаю на доработку.

2019-05-25 13:07 UTC, SashaShip commented
Убрала стейты, но это не помогло.. Подскажите, что ещё проверить? Тревис пишет, что файла не хватает ему packer/variables.json.example, хотя он вроде в директории сущесвтует...

2019-05-28 09:31 UTC, SashaShip commented
Просьба подтвердить

2019-05-28 19:52 UTC, mrgreyves approved these changes
Здравствуйте!) Проверил ваше дз. Хорошо что оставляете комментарии. Дз принимаю!)

2019-05-29 05:19 UTC, merged